name = "count-do"
account_id = "b6641681fe423910342b9ffa1364c76d"
route = { pattern = "*count.do/api*", zone_id = "0660fc2da7196c209e73956a2ffd5965" }
main = "worker.js"
compatibility_date = "2022-08-04"

[durable_objects]
bindings = [{name = "COUNTER", class_name = "Counter"}]

[[migrations]]
tag = "v1" # Should be unique for each entry
new_classes = ["Counter"]